# Generated by Django 3.1 on 2021-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='job',
            field=models.CharField(max_length=300),
        ),
    ]
