# Generated by Django 3.2.3 on 2021-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210327_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('About Us', 'About Us'), ('About Our Services', 'About Our Services'), ('About Our Writers', 'About Our Writers'), ('Help & Support', 'Help & Support')], max_length=300),
        ),
    ]
